source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Dealat-iOS' do

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'AlamofireObjectMapper'
pod 'ObjectMapper'
pod 'SDWebImage'
pod 'Kingfisher'

pod 'SideMenu'
pod 'DropDown'
pod 'DLRadioButton'
pod 'CHIPageControl/Aji'

pod 'DatePickerDialog'
pod 'AFDateHelper'
pod 'Toast-Swift'
pod 'JGProgressHUD'
pod 'KSToastView'
pod 'SwipeBack'

pod 'IQKeyboardManagerSwift'

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'GoogleAnalytics'
#pod 'Google/Analytics'

#pod 'UICheckbox.Swift'


pod 'JVFloatLabeledTextField'
pod 'SkyFloatingLabelTextField'
#pod 'TLPhotoPicker'
pod 'YangMingShan'
pod 'KMPlaceholderTextView'
pod 'XLPagerTabStrip'


pod 'IQDropDownTextField'
pod 'GrowingTextView'#, '~> 0.5.5'
pod 'ActiveLabel'
pod 'Lightbox'
#pod 'Emoji-swift'


pod 'AttributedTextView'#, '~> 1.1.0'

pod 'Fabric'#, '~> 1.7.7'
pod 'Crashlytics'#, '~> 3.10.2'


#pod 'FacebookCore'
#pod 'FacebookLogin'
#pod 'KMPlaceholderTextView'
#pod 'PayPal-iOS-SDK'
#pod 'CardIO'

end
